name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t public.ecr.aws/p2m0e7n7/nodejs:latest .

    




      
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
          registry-type: public

    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
          REGISTRY: public
          REGISTRY_ALIAS: p2m0e7n7
          REPOSITORY: nodejs
          IMAGE_TAG: latest
      run: |
          docker build -t public.ecr.aws/p2m0e7n7/nodejs .
          docker push public.ecr.aws/p2m0e7n7/nodejs


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster hello-world-cluster --service hello-world-service  --force-new-deployment
